---
services: docker

env:
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test.yml
    debug_ansible:
  #- distro: centos6
  #  init: /sbin/init
  #  run_opts: ""
  #  playbook: test.yml

services:
  - docker

before_install:
  # Pull container
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/ansible-role-icinga2:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'
  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-galaxy install geerlingguy.mysql'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-galaxy install geerlingguy.apache'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/ansible-role-icinga2/tests/${playbook} --syntax-check'
  # Running playbook
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm yum install -y epel-release'
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/ansible-role-icinga2/tests/${playbook} ${debug_ansible}'

  # Test role idempotence.
  #- idempotence=$(mktemp)
  #- docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/ansible-role-icinga2/tests/${playbook} | tee -a ${idempotence}
  #- >
  #  tail ${idempotence}
  #  | grep -q 'changed=0.*failed=0'
  #  && (echo 'Idempotence test: pass' && exit 0)
  #  || (echo 'Idempotence test: fail' && exit 1)
  # Make sure that grafana still working

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/